### ISSUE TITLE
ubuntu 16.04 problem?

### ISSUE THREAD

**Issue by jimdowling** [sous-chefs/sysctl#92] opened 2017-08-07 13:04 UTC
### Cookbook version
master

### Chef-client version
12.12.15, chef-solo

### Platform Details
ubuntu 16.04, virtualbox/vagrant

### Scenario:
I am using the LWRP
sysctl::apply_params
and it suddenly stopped working for ubuntu and centos.

### Steps to Reproduce:
  node.default['sysctl']['allow_sysctl_conf'] = true
  node.default['sysctl']['params']['vm']['swappiness'] = 1
  node.default['sysctl']['params']['vm']['overcommit_memory'] = 1
  node.default['sysctl']['params']['vm']['overcommit_ratio'] = 100
  node.default['sysctl']['params']['net']['core']['somaxconn'] = 1024
  include_recipe 'sysctl::apply'

### Expected Result:
This worked until the recent big merge to master.

I think the problem is here:
libraries/sysctl_param.rb:57
The execute block is run during the compile phase, before the template creates the /etc/sysctl.d/99-chef-#{key}.conf file.
I checked and the conf file hasn't been created when the execute block is run:

vagrant@hopsworks0:~/.karamel/install$ ls -artlh /etc/sysctl.d/
total 44K
-rw-r--r--  1 root root  519 Jan 13  2016 README
-rw-r--r--  1 root root  506 Jan 13  2016 10-zeropage.conf
-rw-r--r--  1 root root 1.3K Jan 13  2016 10-ptrace.conf
-rw-r--r--  1 root root  509 Jan 13  2016 10-network-security.conf
-rw-r--r--  1 root root 1.2K Jan 13  2016 10-magic-sysrq.conf
-rw-r--r--  1 root root  257 Jan 13  2016 10-link-restrictions.conf
-rw-r--r--  1 root root  726 Jan 13  2016 10-kernel-hardening.conf
-rw-r--r--  1 root root  490 Jan 13  2016 10-ipv6-privacy.conf
-rw-r--r--  1 root root   77 Jan 13  2016 10-console-messages.conf
lrwxrwxrwx  1 root root   14 Jan 18  2017 99-sysctl.conf -> ../sysctl.conf
drwxr-xr-x  2 root root 4.0K Apr 27 18:03 .
drwxr-xr-x 96 root root 4.0K Aug  7 12:47 ..

### Actual Result:

RuntimeError
------------
Unknown sysctl file location. Unsupported platform.

Cookbook Trace:
---------------
/tmp/chef-solo/cookbooks/sysctl/libraries/helpers_param.rb:32:in `config_sysctl'
/tmp/chef-solo/cookbooks/sysctl/libraries/sysctl_param.rb:57:in `block in create_sysctld'
/tmp/chef-solo/cookbooks/sysctl/libraries/sysctl_param.rb:56:in `create_sysctld'
/tmp/chef-solo/cookbooks/sysctl/libraries/sysctl_param.rb:67:in `block (2 levels) in <class:SysctlParam>'
/tmp/chef-solo/cookbooks/sysctl/libraries/sysctl_param.rb:64:in `block in <class:SysctlParam>'

Resource Declaration:
---------------------
# In /tmp/chef-solo/cookbooks/sysctl/recipes/default.rb

 26:   sysctl_param k do
 27:     value v
 28:   end
 29: end if node.attribute?('sysctl') && node['sysctl'].attribute?('params')

Compiled Resource:
------------------
# Declared in /tmp/chef-solo/cookbooks/sysctl/recipes/default.rb:26:in `block in from_file'

sysctl_param("net.core.somaxconn") do
  action [:apply]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :sysctl_param
  cookbook_name "sysctl"
  recipe_name "default"
  value "1024"
  key "net.core.somaxconn"
end

Platform:
---------
x86_64-linux

**Comment by aalmenar** [comment] 2017-08-23 10:57
This happens also on Debian 9.x, Debian 8.x

       Recipe: sysctl::default
         * sysctl_param[net.ipv4.conf.all.rp_filter] action apply

           ================================================================================
           Error executing action `apply` on resource 'sysctl_param[net.ipv4.conf.all.rp_filter]'
           ================================================================================

           RuntimeError
           ------------
           Unknown sysctl file location. Unsupported platform.

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/sysctl/libraries/helpers_param.rb:32:in `config_sysctl'
           /tmp/kitchen/cache/cookbooks/sysctl/libraries/sysctl_param.rb:57:in `block in create_sysctld'
           /tmp/kitchen/cache/cookbooks/sysctl/libraries/sysctl_param.rb:56:in `create_sysctld'
           /tmp/kitchen/cache/cookbooks/sysctl/libraries/sysctl_param.rb:67:in `block (2 levels) in <class:SysctlParam>'
           /tmp/kitchen/cache/cookbooks/sysctl/libraries/sysctl_param.rb:64:in `block in <class:SysctlParam>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/sysctl/recipes/default.rb

            26:   sysctl_param k do
            27:     value v
            28:   end
            29: end if node.attribute?('sysctl') && node['sysctl'].attribute?('params')

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/sysctl/recipes/default.rb:26:in `block in from_file'

           sysctl_param("net.ipv4.conf.all.rp_filter") do
             action [:apply]
             default_guard_interpreter :default
             declared_type :sysctl_param
             cookbook_name "sysctl"
             recipe_name "default"
             value "1"
             key "net.ipv4.conf.all.rp_filter"
           end

           System Info:
           ------------
           chef_version=13.3.42
           platform=debian
           platform_version=8.8
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=1204;start=10:48:37;
           executable=/opt/chef/bin/chef-client


Declared on my cookbook attributes:

default['sysctl']['params']['net']['ipv4']['conf']['all']['rp_filter'] = 1
default['sysctl']['params']['net']['ipv4']['conf']['default']['rp_filter'] = 1

and on my default recipe:

include_recipe 'sysctl::default'
include_recipe 'sysctl::apply'

**Comment by jblaine** [comment] 2017-09-18 15:32
This happens on RHEL 6 and 7 as well :(

**Comment by damacus** [comment] 2017-10-17 20:03
Any way any of you can write a test for this so we can look at fixing it for the future please?

**Comment by brettrann** [comment] 2018-01-02 03:34
https://github.com/sous-chefs/sysctl/blob/fa101c34c2d8cd68c24c35f5998003cb9802f077/libraries/helpers_param.rb#L30

the default conf file location is only specified for freebsd and suse, otherwise it will bail out. 

it can be overrided with conf_file but probably should have more defaults than just those two.

**Comment by damacus** [comment] 2018-01-30 09:34
Hi @brettrann @aalmenar do either of you have time to write an inspec test to reproduce this please?

**Comment by cholman-zd** [comment] 2018-02-01 05:12
Hi @damacus , I don't have time or knowledge of inspec to write an inspec test (sorry) but ran in to this problem too. My work around was setting `node['sysctl']['conf_file']` in order to short circuit `config_sysctl` in [this file](https://github.com/sous-chefs/sysctl/blob/d29c2846dceb4bf834ab182c7c8c7982565e151c/libraries/helpers_param.rb#L25)

You should set default sysctl locations for other OSs [here](https://github.com/sous-chefs/sysctl/blob/d29c2846dceb4bf834ab182c7c8c7982565e151c/libraries/helpers_param.rb#L27) since as far as I can tell that attribute never gets set (this cookbook has no default attributes?), so if the user does not set that attribute themselves, then this cookbook will always crash on anything except BSD/Suse.

**Comment by MarkGibbons** [comment] 2018-02-01 05:40
I'll take a shot at coding the test.

**Comment by MarkGibbons** [comment] 2018-02-01 06:35
I think the cookbook is working correctly.

By default arch, debian, rhel, fedora, amazon and suse > 12.0 use /etc/sysctl.d.
By specifying node.default['sysctl']['allow_sysctl_conf'] = true an attempt is made to combine all of the files in /etc/sysctl.d and copy them to the default config_sysctl (/etc/sysctl.conf ) file.  That doesn't seem like a reasonable thing to do.  The files will still be in /etc/sysctl.d and the contents will be in /etc/sysctl.conf duplicating the settings.

If someone wants to override the default behavior by using node.default['sysctl']['allow_sysctl_conf'] = true, they also need to specify node['sysctl']['conf_file'] for the platform families that use /etc/sysctl.d.

I have a test case written, but I think the fix is to specify node['sysctl']['conf_file'].

Am I missing something?
Thanks,
   Mark

**Comment by damacus** [comment] 2018-02-17 18:22
I'm going to close this down now as we have test coverage for Debian, CentOS/RHEL etc mentioned in this issue. 

If you this this is incorrect please reopen, with information from the latest version of the cookbook. 

Thank you!

**Closed by damacus** 2018-02-17 18:22 UTC
Labels: Priority: Medium, Status: Pending Contributor, Type: Bug, help wanted
